project:
  type: website
  output-dir: docs

website:
  title: "Marvin King"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: classes.qmd
        text: Classes
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About
      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



